import '@/styles/globals.css';
import { Manrope } from 'next/font/google';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${manrope.className}`}
    >
      <body className="bg-black text-primary">
        {' '}
        <div className="text-4xl font-bold grid grid-rows-2">
          <div className="text-center">
            supa<span className="text-secondary ">goal</span>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
